@Web_HostAddress = http://localhost:8080

@BearerToken = {{BearerToken}} 

###

# CreateBrand

POST {{Web_HostAddress}}/api/Brands
Authorization: Bearer {{BearerToken}} 
Content-Type: application/json

{
  "name": "Demo Brand"
}

###

# CreateSeries

POST {{Web_HostAddress}}/api/Series
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "brandId": "{{brandId}}",
  "name": "Demo Series3"
}

###

# GET ProductItems
GET {{Web_HostAddress}}/api/ProductItems?
    Brand=Artfloor&
    Series=Urban&
    PageNumber=1&
    PageSize=10

###


# GET All ProductItems
GET {{Web_HostAddress}}/api/ProductItems?
    PageNumber=1&
    PageSize=10

###

# POST ProductItems
POST {{Web_HostAddress}}/api/ProductItems
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "seriesId": "{{seriesId}}", 
  "name": "Sample Product",
  "price": 99.99,
  "image": "sample-image-url",
  "detail": "Sample product detail"
}


###

# GET Brands
GET {{Web_HostAddress}}/api/Brands

//set first brand id to brandId, and set first series id to seriesId
> {% 
  const brands = response.body;
  const firstBrand = brands[0];
  const firstSeries = firstBrand.series[0];
  client.global.set("brandId", firstBrand.id);
  client.global.set("seriesId", firstSeries.id);
%}
