@Web_HostAddress = http://localhost:8080

@BearerToken = {{BearerToken}} 

###

# CreateBrand

POST {{Web_HostAddress}}/api/Brands
Authorization: Bearer {{BearerToken}} 
Content-Type: application/json

{
  "name": "Demo Brand"
}

###

# CreateSeries

POST {{Web_HostAddress}}/api/Series
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "brandId": "00000000-0000-0000-0000-000000000000",
  "name": "Demo Series"
}

###

# GET Brands
GET {{Web_HostAddress}}/api/Brands
Authorization: Bearer {{BearerToken}}


###

# GET ProductItems
GET {{Web_HostAddress}}/api/ProductItems?
    Brand=Artfloor&
    Series=Urban&
    PageNumber=1&
    PageSize=10

###

# POST ProductItems
POST {{Web_HostAddress}}/api/ProductItems
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "seriesId": "00000000-0000-0000-0000-000000000000",
  "name": "Sample Product",
  "price": 99.99,
  "image": "sample-image-url",
  "detail": "Sample product detail"
}

